import numpy as np
my_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_arr)
print(my_arr.ndim)
print(my_arr.itemsize)
print(my_arr.dtype)
print(my_arr.shape)
print(my_arr.reshape(1,9))
#slicing
print(my_arr[2][2])
print(my_arr.max())
print(my_arr.min())
print(my_arr.sum())
print(my_arr.max(axis=0))
print(my_arr.sum(axis=1))
print(np.sqrt(my_arr))
print(np.std(my_arr))
a = np.array([[1,2,30],[10,15,4]])
b = np.array([[1,2,3],[12, 19, 29]])
print("Sum of array a and b\n",a+b)
print("Product of array a and b\n",a*b)
print("Division of array a and b\n",a/b)
